### ISSUE TITLE
Error for using NetGear when sending frame together with additional data

### ISSUE THREAD

**Issue by michaelhku2002** [abhiTronix/vidgear#104]
Hi, the problem stated in #102  has been solved that I can view the stream. Thanks for your help. Then I tried to add one more thing--sending additional random number for testing of implementation of sending real-time data later on. 

## Question

However, when I referred to the examples for exclusive modes for adding the additional random number to be send through message parameter i.e. 
client.send(frame,message=realtime_data)

The following error has been caught:

```
Traceback (most recent call last):
  File "webstreaming_server_view.py", line 38, in get_frame
    image,realtime_data=data
ValueError: too many values to unpack (expected 2)
```

Then I looked at the netgear.py file, finding that in the function recv(), it just simply gets all received data and I cannot get any idea of how to solve the problem as stated in the above error.

I attached the two files for my main program in the zip file, and hope there can be any hint for solving such problem. Thanks!

[webstreaming.zip](https://github.com/abhiTronix/vidgear/files/4146730/webstreaming.zip)

### Acknowledgment

- [ + ] A brief but descriptive Title of your issue.
- [ + ] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [ + ] I have read the [FAQ](https://github.com/abhiTronix/vidgear/wiki/FAQ-&-Troubleshooting).
- [ + ] I have read the [Wiki](https://github.com/abhiTronix/vidgear/wiki#vidgear).

### Your Environment

* VidGear version: 0.1.6
* Branch: Master
* Python version: 3.7.3
* pip version: 18.1
* Operating System and version: Debian 10 (buster) on Raspberry Pi

**Comment by abhiTronix** [comment]
> However, when I referred to the examples for exclusive modes for adding the additional random number to be send through message parameter i.e.
> client.send(frame,message=realtime_data)
> 
> The following error has been caught:
> 
> Traceback (most recent call last):
>   File "webstreaming_server_view.py", line 38, in get_frame
>     image,realtime_data=data
> ValueError: too many values to unpack (expected 2)

**@michaelhku2002 Did you even read the [Bidirectional Mode: Bidirectional Data Transfer in NetGear API](https://github.com/abhiTronix/vidgear/wiki/Bidirectional-Mode:-Bidirectional-Data-Transfer-in-NetGear-API#bi-directional-mode-bidirectional-data-transfer-in-netgear-api) Wiki? You're clearly using wrong code to transmit additional data with NetGear API. Kindly read this wiki and try again, since you're not activating this mode `options = {'bidirectional_mode': True}` in your script.**

**Comment by michaelhku2002** [comment]
Thanks!
Now it works. So, would you mind updating the Wiki that the primary mode cannot be used for sending additional data along with video frame so that it would be clearer? 
By the way, as my example does not need to send back the message to client, would you mind me sharing my example later on for other's reference? Thanks again!
Cheers,Michael    Abhishek Thakur (<notifications@github.com>) 在 2020年2月3日星期一 下午07:41:01 [GMT+8] 寫道：  
 
 
Closed #104.

**Comment by abhiTronix** [comment]
> So, would you mind updating the Wiki that the primary mode cannot be used for sending additional data along with video frame so that it would be clearer? 

@michaelhku2002 Ok, Where did you read _"primary mode CAN be used for sending additional data"_ on [NetGear API](https://github.com/abhiTronix/vidgear/wiki/NetGear#netgear-api) Wiki? and btw there are no example code that is sending data along with frame on this wiki page. You must need to enable [exclusive modes](https://github.com/abhiTronix/vidgear/wiki/NetGear#modes-of-operation) to be able to use any of the advanced features, which are clearly not meant for everyone and that's why placed on a seperate Wiki Page.   

> By the way, as my example does not need to send back the message to client

That's not true. Even when you're not sending any  data the NetGear API itself is sending delivery confirmation in the background. NetGear API keeps check empty data quietly in the background and thereby handles every error robustly.

**Comment by michaelhku2002** [comment]
1. I found here
"PRIMARY MODES: NetGear API primarily has two modes of operations:
Send Mode: which employs send() function to send video frames over the network only. You can also use this function to send additional data (along with video frames). Activate this mode by setting receive_mode = False." Maybe I misunderstand about the bold sentence.

2. Thanks for your explanation in the last paragraph about the confirmation.

    Abhishek Thakur (<notifications@github.com>) 在 2020年2月3日星期一 下午09:31:53 [GMT+8] 寫道：  
 
 

So, would you mind updating the Wiki that the primary mode cannot be used for sending additional data along with video frame so that it would be clearer?


@michaelhku2002 Ok, Where did you read "primary mode CAN be used for sending additional data" on NetGear API Wiki? and btw there are no example code that is sending data along with frame on this wiki page. You must need to enable exclusive modes to be able to use any of the advanced features, which are clearly not meant for everyone and that's why placed on a seperate Wiki Page.


By the way, as my example does not need to send back the message to client


That's not true. Even when you're not sending any data the NetGear API itself is sending delivery confirmation in the background. NetGear API keeps check empty data quietly in the background and thereby handles every error robustly.

**Comment by abhiTronix** [comment]
> Send Mode: which employs send() function to send video frames over the network only. You can also use this function to send additional data (along with video frames). Activate this mode by setting receive_mode = False." Maybe I misunderstand about the bold sentence.

Corrected.
