### ISSUE TITLE
How to enable zmq.noBlocking  for the client

### ISSUE THREAD

**Issue by ismael694** [abhiTronix/vidgear#128]
## Question

Hi. I used your library to do some video streaming. I tried to enable the zmq.noBlocking option on the client side so that the recv function is not blocking, by setting the flag = 1 but I get the following error:
**zmq.error.Again: Resource temporarily unavailable.**
What should I do? Are there other ways to make the recv function non-blocking?
Thanks for your help,
Yours sincerely,
IC

**Comment by abhiTronix** [comment]
> I tried to enable the zmq.noBlocking option on the client side so that the recv function is not blocking, by setting the flag = 1 but I get the following error:
zmq.error.Again: Resource temporarily unavailable.

@ismael694  In concurrent environments there are no guarantees about the order of execution of independent processes. Even though you are responding immediately to the message on the Server end, the response may not get to the receiving socket at client's end before you call `socket.recv`. Basically, When you call `socket.send` the message needs to go over the network to your server, the server needs to create the message and respond and then the message needs to go back over the network to your client code. The time to send the messages over the network will be quite long and you are calling `socket.recv` immediately after `socket.send`.

So in fact when you call `message = socket.recv(flags=zmq.NOBLOCK)` the Client's end  socket will not have received the *Acknowledgment* from the Server end yet, and since you are using `NOBLOCK` with no messages have been received on the socket, therefore, it resulting in this error.

Also, `NOBLOCK` is likely not appropriate in this scenario. You can experiment with this by adding a `time.sleep(time_delay)` call in between `send` and `recv` to show that the time delay of waiting for the response from the Server is indeed the issue but that will defeat the purpose in your case.

</br>

> Are there other ways to make the recv function non-blocking?

Yes, it's simple, just use [`pattern=2`](https://github.com/abhiTronix/vidgear/wiki/NetGear#parameters-and-attributes-wrench) in your script, which is [`zmq.PUB/zmq.SUB`](https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pubsub.html) (ZMQ Publish/Subscribe Pattern) with NetGear API. In this pattern, both Server and Client end works independently and messages are published without the knowledge of what or if any subscriber of that knowledge exists. No single publisher overwhelms the subscriber. The messages from both publishers are interleaved.

**Comment by ismael694** [comment]
Thank you for your help. By adding a delay between the server and the
client, the option zmq.no block works well. Thank you for the explication .
The second option with pattern =2 works perfectly too.
Sincerely,
IC

Le jeu. 7 mai 2020 à 11:15, Abhishek Thakur <notifications@github.com> a
écrit :
