### ISSUE TITLE
Real-time stabilization on incoming frames, but not passing capture source object directly into VideoGear

### ISSUE THREAD

**Issue by AlexYiningLiu** [abhiTronix/vidgear#156]
## Question

Can this code be implemented to work on real-time incoming frames? The frames are not captured by 
```
stream = VideoGear(source=0, stabilize = True).start()
```
Instead, they will be received as numpy arrays through reading from a disk location frame by frame. Can I still use Vidgears to perform stabilization? Thanks. 

### Acknowledgment

https://stackoverflow.com/questions/51970072/real-time-video-stabilization-opencv

### Your Environment

* VidGear version: 
* Branch: 
* Python version:
* pip version:
* Operating System and version:

**Comment by abhiTronix** [comment]
@AlexYiningLiu Absolutely yes, that what [Stabilizer Class](https://abhitronix.github.io/vidgear/gears/stabilizer/overview/) built for. That's why it is advised to always check [Vidgear Docs](https://abhitronix.github.io/vidgear/) before raising an issue here. Also, please fill [Issue template](https://abhitronix.github.io/vidgear/contribution/issue/) before raising one. See [Stabilizer Class docs](https://abhitronix.github.io/vidgear/gears/stabilizer/usage/)
