### ISSUE TITLE
Possible to send/receive frame metadata (eg capture time) via netgear?

### ISSUE THREAD

**Issue by whogben** [abhiTronix/vidgear#171]
## Question

Is it possible to send arbitrary metadata along with the video frames via netgear, for example a frame number to sync up frames with other data?

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [FAQs](https://abhitronix.github.io/vidgear/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).

### Context

I am streaming from a raspberry pi based robot to an external controller that will perform additional frame analysis, and I'd like to figure out when each frame was captured on the bot so I can marry them up to accelerometer and other data. I can send the other data separately, so even just a frame number could work. I'm open to other approaches too. Many thanks in advance for your attention.

**Comment by whogben** [comment]
I apologize, I missed this when I was looking in the documentation:

https://abhitronix.github.io/vidgear/gears/netgear/advanced/bidirectional_mode/

This question issue can be closed.

**Comment by abhiTronix** [comment]
>  I have left is: is there a way to disable the reply, so there's no additional latency waiting for it, as there will be no replies in my case and latency is important. 

@whogben There's no additional latency unless the data being sent along with frames is huge or your network bandwidth is small or vice versa. Plus, it never waits for messge/data when sending frames, API is smart enough to sense data and then just sends without any delay in sending frames, both works independently.  Also,there's no need to mix netgear with netgear_async, as it may cause more delay due to network conjuction.

**Comment by abhiTronix** [comment]
@whogben join our [Gitter Chat](https://gitter.im/vidgear/community?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications), for discussing simple queries.
