### ISSUE TITLE
Fallback download for FFmpeg static fails

### ISSUE THREAD

**Issue by alexagv** [abhiTronix/vidgear#204]
## Description

The main [URL](https://github.com/abhiTronix/vidgear/blob/b882e7b8473fe96fe6c8d9afedf3b3998f9c5ed0/vidgear/gears/helper.py#L657) for FFmpeg static libs are deprecated since Sept 18 2020.
I know there is a backup URL to your repo. However, it sometimes seems this either times out or something else happens causing compression mode to disable.

### Acknowledgment

- [x] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear).
- [x] I have read the [Issue Guidelines](https://abhitronix.github.io/vidgear/contribution/issue/#submitting-an-issue-guidelines).

### Environment

* VidGear version:  0.2.0
* Branch: 
* Python version:  3.8
* PiP version: 
* Operating System and version: Windows 10 Pro 1909

### Expected Behavior

If the primary URL fails, I expect the secondary to work

### Actual Behavior

Primary URL fail, logger reports trying to download from Git but jumps straight to "Disabling Compression Mode"

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ffmpeg.zeranoe.com', port=443): Max retries exceeded with url: /builds/win64/static/ffmpeg-latest-win64-static.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001AF20B9A3A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
21:24:57 :: Helper :: WARNING :: Downloading Failed. Trying GitHub mirror now!
21:24:59 :: WriteGear :: WARNING :: Disabling Compression Mode since no valid FFmpeg executables found on this machine!
```

### Possible Fix

Update primary URL to https://www.gyan.dev/ffmpeg/builds/ or your own repo (?) and look at fallback logic why it doesn't wait for secondary URL download

### Steps to reproduce

(Write your steps here:)

1. Run [GyroFlow](https://github.com/ElvinC/gyroflow/releases/tag/0.2.1-alpha) on a Windows 10 machine

**Comment by abhiTronix** [comment]
@alexagv This issue is already fixed in commit https://github.com/abhiTronix/vidgear/commit/20132cf4ba653a8d6cb47326caeecc675468ca83 of `testing` branch, and now a permanent new [**Automated Latest FFmpeg Mirror**](https://github.com/abhiTronix/FFmpeg-Builds) is up and running for all future releases. 

So either you can install testing branch as follows, to try this patches earlier:

```sh
  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testing branch
  git checkout testing

  # install normally
  pip install .

  # OR install with asyncio support
  pip install .[asyncio]
```
OR wait for next `v0.2.1` release.

**Comment by abhiTronix** [comment]
> However, it sometimes seems this either times out or something else happens causing compression mode to disable.

@alexagv  I'm curious about this. Can you reproduce this bug with `logging=True`. Thanks.

**Comment by alexagv** [comment]
Ah thanks, will update and test. I had several users report on the issue, so will have a look with the logger enabled 👍

**Comment by abhiTronix** [comment]
@alexagv, Thanks. I just tested this on latest Windows Preview build and `testing` branch worked without any issue. The only possible scenario if a bug can exist, is GitHub domain blocked or down in your region. If it is blocked, then proxy settings can work with `request` module. I'm waiting for your results and then I'll make changes accordingly. Goodluck.

**Comment by abhiTronix** [comment]
@alexagv I think the bug was `logging` flag that simply discards/hides any download errors when logging is disabled. 
https://github.com/abhiTronix/vidgear/blob/7018d166ddcdb5f585225b79cf87d0ef335cb550/vidgear/gears/helper.py#L593-L600
Also I've added the new robust [session approach](https://github.com/abhiTronix/vidgear/commit/9c07deaef73e5a9a55eee6edb422608dabdea894) for downloading with automatic retry and timeout. It should work now without any hassle. You can try this patch:
```sh
  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testing branch
  git checkout development

  # install normally
  pip install .

  # OR install with asyncio support
  pip install .[asyncio]
```
Again, Thanks you for reporting this bug.

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/8a0c2af320c8d57d5377ad383999cf5ee7c55097**
