### ISSUE TITLE
Low fps for 8k videos

### ISSUE THREAD

**Issue by wjassim** [abhiTronix/vidgear#234]
Hi, 
Thank you for providing this awesome tool. It is very useful and handy. 

I was running the following code given in VideoGear API Usage Examples to read and display frames from a high resolution (8k, w=8192, h=4320) video:

from vidgear.gears import VideoGear
import cv2
stream = VideoGear(source="8k.avi").start()
while True:
    frame = stream.read()
    if frame is None:
        break
    #### {do something with the frame here}
    cv2.imshow("Output Frame", frame)
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break
cv2.destroyAllWindows()
stream.stop()

and it worked well but provided very low fps (around 6.3 fps, time=87.26 s for 533 frames). Sorry for the random question but I was wondering if it is possible to modify some parameters in vidgear or to suggest an alternative manner to gain higher fps . Thanks a million.

**Comment by abhiTronix** [comment]
@wjassim Actually its not vidgear but your OpenCV that is bottlenecking the performance. Since OpenCV is taking too long to process each frame because of huge sized 8K frames, there's nothing vidgear can do to squeeze performance out of it.  You can only see greater performance if you sacrifice 8K quality and switch to 1080p or so.  

**However, if you can [compiling OpenCV manually and use GPU enabled CUDA backend](https://github.com/abhiTronix/vidgear/issues/69#issuecomment-551112764), you can easily achieve far better FPS performance with 8K frames too.**


Also, in the future when issue #148 is resolved, you can use vidgear directly to decode 8K videos in seconds. So stay tuned.
