### ISSUE TITLE
TLS Connection was non-properly terminated

### ISSUE THREAD

**Issue by keyvdir** [abhiTronix/vidgear#25]
Hi, i want to get live stream from youtube using my raspberry pi. But, i got output:

`The TLS connection was non-properly terminated.
The specified session has been invalidated for some reason.`

Please help me

**Comment by abhiTronix** [comment]
Kindly, Share the **YouTube URL** that you're trying to play via vidgear.

**Comment by keyvdir** [comment]
https://www.youtube.com/watch?v=rWV00JA89No this is the Youtube live streaming url that i want to use. The video is shown on my Rasbpberry Pi, but it will get delayed repeatedly after one line of 
`The TLS connection was non-properly terminated. The specified session has been invalidated for some reason.`

**Comment by abhiTronix** [comment]
@keyvdir There is some problem with this  https://www.youtube.com/watch?v=rWV00JA89No live video. It is buffering a lot even on my High-Speed Connection on my powerful ubuntu machine when played on chrome/Mozilla Browser too. This problem is either related to Video itself or with YouTube server end and has nothing to do with `vidgear` library. You can test any other live stream video URL of this channel and it will work normally for e.g. https://youtu.be/YYO9rhI5ins

**Comment by abhiTronix** [comment]
**Closed. Feel free to reopen if it doesn't work for you.**
