### ISSUE TITLE
How to get the minimum version required for each package to install VidGear

### ISSUE THREAD

**Issue by Adib234** [abhiTronix/vidgear#267]
## Question

A project that I'm working gets performance boosts from using VidGear but would like to know what is the minimum version of all the packages that VidGear uses since they provide the minimum versions in their `requirements.txt`

### Acknowledgment

- [X] I have searched the [issues](https://github.com/abhiTronix/vidgear/issues) for my issue and found nothing related or helpful.
- [X] I have read the [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).

### Your Environment

* VidGear version: 
* Branch: 
* Python version: 
* PiP version: 
* Operating System and version:

**Comment by zpapakipos** [comment]
Note here (I’m a maintainer of the project that would like to add vidgear to our dependencies): can you guys please change your requirements to just set a minimum version for each of dependency, instead of requiring **the most recent version** for many of them? I doubt you actually need the most recent versions, and it makes it way heavier to install vidgear if we have to download new versions of all the dependencies.

I’m sure this would be a helpful change for other projects that use vidgear too. Thanks in advance!

**Comment by abhiTronix** [comment]
> Note here (I’m a maintainer of the project that would like to add vidgear to our dependencies): can you guys please change your requirements to just set a minimum version for each of dependency, instead of requiring the most recent version for many of them? I doubt you actually need the most recent versions, and it makes it way heavier to install vidgear if we have to download new versions of all the dependencies.

@zpapakipos Thank you for trusting vidgear, I agree with you that simple `requirement.txt` will be more suitable. But there's a catch:

This behavior doesn't affect the generated [wheel package or tar package in release](https://github.com/abhiTronix/vidgear/releases/tag/vidgear-0.2.3)  or [official pypi package](https://pypi.org/project/vidgear/), since the wheel(`.whl`) file generated will have automatically have minimum requirement defined in `requires.txt` file. **You can easily verify this by extracting the [`vidgear-0.2.3.tar.gz` release file](https://github.com/abhiTronix/vidgear/releases/download/vidgear-0.2.3/vidgear-0.2.3.tar.gz):**

![image](https://user-images.githubusercontent.com/34266896/142962508-a4e93342-f174-4b09-b403-af76fede1c71.png)

**hence, the aim behind getting most recent version for some packages is to bypass manually defining version in `requirement.txt` for those packages when the wheel is generated.**


&nbsp;


### But why dynamic behavior at all and not just `requirement.txt`:

Because vidgear is handling many packages from different domains at its backend, therefore there are many challenges to just adding  `requirement.txt`. And here's why dynamic approach need for it: 
- The most prominant reason it that we cannot define some dependency in requirement  like `opencv-python` as it can conflict with OpenCV installed from source. But it is critical for vidgear's core functioning.
- Moreover, Dependencies like `picamera` and `uvloop` are platform specific.
- and Dependency like `uvloop` doesn't support python 3.6.x legacies. (Will be resolved in #255) 

&nbsp;

### Solution:
> A project that I'm working gets performance boosts from using VidGear but would like to know what is the minimum version of all the packages that VidGear uses since they provide the minimum versions in their requirements.txt

The simplest solution to this problem is to just add `requires.txt` as `requirement.txt` in the project.

**Comment by abhiTronix** [comment]
@zpapakipos Also I want to inform you that you do not need all the dependencies for your project, if you're using on a specific API, then **you can just install specific dependencies required by the API in use except for some Core dependencies:**

- Here are all the **Core dependencies**:

    ```sh
    # Install core dependencies
    pip install cython, numpy, requests, tqdm, colorlog

    # Install opencv(only if not installed previously)
    pip install opencv-python 
    ```

- And here are all **API-specific dependencies** required by API(in use):


    | APIs | Dependencies |
    |:---:|:---|
    | CamGear | `pafy`, `yt_dlp`, `streamlink` |
    | PiGear | `picamera` |
    | VideoGear | - |
    | ScreenGear | `mss`, `pyscreenshot`, `Pillow` |
    | WriteGear | **FFmpeg:** See [this doc ➶](https://abhitronix.github.io/vidgear/v0.2.2-dev/gears/writegear/compression/advanced/ffmpeg_install/#ffmpeg-installation-instructions)  |
    | StreamGear | **FFmpeg:** See [this doc ➶](https://abhitronix.github.io/vidgear/v0.2.2-dev/gears/streamgear/ffmpeg_install/#ffmpeg-installation-instructions) |
    | NetGear | `pyzmq`, `simplejpeg` |
    | WebGear | `starlette`, `jinja2`, `uvicorn`, `simplejpeg` |
    | WebGear_RTC | `aiortc`, `starlette`, `jinja2`, `uvicorn` |
    | NetGear_Async | `pyzmq`, `msgpack`, `msgpack_numpy`, `uvloop` |

**Comment by abhiTronix** [comment]
@zpapakipos @Adib234 Please let me know if given solution in  https://github.com/abhiTronix/vidgear/issues/267#issuecomment-976109207 is adequate?

**Comment by zpapakipos** [comment]
Hi @abhiTronix thanks for your response!

I understand your point that I could ‘pip install —no-deps’ & only install the dependencies I need for the API calls we’re using. However to install ’vidgear’ internally in our company’s code base, we aren’t able to set flags like ‘—no-deps’.

I was hoping you could modify your ‘setup.py’ file. You can define an extra like you’ve done for ‘asyncio’, for the dependencies that are only required for certain functionality. And in the ‘install_requires’ you can shorten the list of dependencies to just the core ones you listed above: cython, numpy, requests, tqdm, colorlog, opencv-python, and only specify minimum versions **if necessary** (I don’t think it’s necessary to require the most recent version of so many packages as you currently). This would solve our problem. Would that be possible for you to do?

**Comment by abhiTronix** [comment]
I was hoping you could modify your setup.py file. You can define an extra like you’ve done for asyncio, for the dependencies that are only required for certain functionality. And in the install_requires you can shorten the list of dependencies to just the core ones you listed above: cython, numpy, requests, tqdm, colorlog, opencv-python

@zpapakipos Sounds good to me. Let's do this!

**Comment by zpapakipos** [comment]
Thanks @abhiTronix, glad to hear you're onboard! :) I just published a PR making the changes I had in mind to `setup.py`: https://github.com/abhiTronix/vidgear/pull/268

Can you please take a look & test it out? I wrote the steps in the PR description. The sooner that we can update `vidgear` on pypi the sooner we can start using `vidgear` in our project. Thanks!

**Comment by abhiTronix** [comment]
@zpapakipos changes mentioned in https://github.com/abhiTronix/vidgear/pull/268#pullrequestreview-814359278 must be resolved in order to merge your PR.

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit https://github.com/abhiTronix/vidgear/commit/e94ec7f0158e6fec6c7cc9b24dff478d2ce01b14**

**Comment by zpapakipos** [comment]
Hi @abhiTronix checking in, when do you expect to get v0.2.4 out so we can benefit from the fix we made? :)

**Comment by abhiTronix** [comment]
@zpapakipos It will happen soon and I'm working on it in my free time. There're a lot of things needed to sort out before making a release, as many packages depend on this library. Please be patient, I'll notify you here.

**Comment by abhiTronix** [comment]
@zpapakipos Thank you for your patience and apologies for the delay. **The latest vidgear `v0.2.4` is now available on pypi with purposed fix: https://pypi.org/project/vidgear/** Goodluck.
