### ISSUE TITLE
[Question]: webgear RTC quality issue 

### ISSUE THREAD

**Issue by AbdulrahmanSoliman1** [abhiTronix/vidgear#323]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

hi thanks for your great work in webgear_RTC

when I compare opencv imshow windows quality with , webgear_rtc Webpage  the quality on the webpage is bad and worse
is there any solution to make the quality same as the imshow ?
![Screenshot_5](https://user-images.githubusercontent.com/108452571/178115705-36d413ad-79df-494c-b29e-e01451043337.png)

my setting is 

> `options = {"custom_stream": Custom_Stream_Class(),"CAP_PROP_FRAME_WIDTH":1280, "CAP_PROP_FRAME_HEIGHT":720,"frame_size_reduction": 0,"CAP_PROP_FPS": 30,"CAP_PROP_BUFFERSIZE": 0}
web = WebGear_RTC(logging=True, **options,resolution=(1280,720),framerate=30)`

### VidGear Version

0.2.5

### Python version

3.9

### Operating System version

windows

**Comment by abhiTronix** [comment]
> webgear_rtc Webpage the quality on the webpage is bad and worse

Thsis has nothing to do with vidgear, this is solely because how [`aiortc`](https://github.com/aiortc/aiortc)(that act as WebGear_RTC backend) works right now. See I'm quoting [the author of aiortc](https://github.com/aiortc/aiortc/discussions/733#discussioncomment-2964709):

> aiortc will send out whatever size frames you give it.
> Regarding the bitrate / frame rate there is currently no API in aiortc to control this.

This means **_`aiortc` can control Size(Resolution) but not Bitrate and Frame rate._** And that's why quality sucks.  

### Why Bitrate and Frame rate also important for quality in WebRTC?

![](https://bloggeek.me/wp-content/uploads/2021/08/202108-webrtc-video-quality.gif)

Video quality in WebRTC is like a 3-legged stool. With all things considered equal, you can tweak the bitrate, frame rate and resolution. At least that’s what you have at your disposal dynamically in real-time when you are in the middle of a session and need to make a decision. There's a blog specifically about this: https://bloggeek.me/tweaking-webrtc-video-quality-unpacking-bitrate-resolution-and-frame-rates/ 


> resolution=(1280,720),framerate=30

Btw, You don't need to define these parameters, these are meant only when using PiGear backend.
