### ISSUE TITLE
[Question]: looping?

### ISSUE THREAD

**Issue by aronchick** [abhiTronix/vidgear#391]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

Great software - thank you!

QQ - is there a way to customize the "the end" screen? and/or is there a way to loop?

### VidGear Version

0.3.2

### Python version

3.10.5

### Operating System version

Ubuntu 20.04p

**Comment by abhiTronix** [comment]
> QQ - is there a way to customize the "the end" screen? and/or is there a way to loop?

@aronchick There's no direct way to customize "the end" screen but you could go on forever with [`enable_infinite_frames`](https://abhitronix.github.io/vidgear/v0.3.1-stable/gears/webgear/params/#webgear-specific-attributes) optional boolean parameter, it can be used to continue streaming (instead of terminating immediately) with emulated blank frames with text "No Input", whenever the input source disconnects.  

Most optimal way would be to create your own producer: https://abhitronix.github.io/vidgear/v0.3.1-stable/gears/webgear/advanced/#using-webgear-with-a-custom-sourceopencv
