### ISSUE TITLE
[Question]: Incompatible License Due to Dependency on GPLv2 Libraries

### ISSUE THREAD

**Issue by REBAUD** [abhiTronix/vidgear#425]
### Issue guidelines

- [X] I've read the [Issue Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/issue/#submitting-an-issue-guidelines) and wholeheartedly agree.

### Issue Checklist

- [X] I have searched open or closed [issues](https://github.com/abhiTronix/vidgear/issues) for my problem and found nothing related or helpful.
- [X] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest) and found nothing related to my problem.
- [X] I have gone through the [Bonus Examples](https://abhitronix.github.io/vidgear/latest/help/get_help/#bonus-examples) and [FAQs](https://abhitronix.github.io/vidgear/latest/help/get_help/#frequently-asked-questions) and found nothing related or helpful.

### Describe your Question

Description: VideoGear is currently licensed under the Apache-2.0 license. However, I noticed that VideoGear depends on yt-dlp, which in turn relies on mutagen, a library licensed under GPLv2. Since the GPLv2 license is incompatible with Apache-2.0 for redistribution in certain contexts, this creates a licensing conflict for using VideoGear in production.

Request: Is it possible to either:

Replace yt-dlp (or mutagen) with alternatives that have more permissive licenses, or
Adjust the dependencies in a way that removes this conflict?
This change would help make VideoGear more viable for production use in projects requiring Apache-2.0 compatibility.

Thank you!

### VidGear Version

3.3.0

### Python version

3.11

### Operating System version

ubuntu 24.04

**Comment by abhiTronix** [comment]
> Description: VideoGear is currently licensed under the Apache-2.0 license. However, I noticed that VideoGear depends on yt-dlp, which in turn relies on mutagen, a library licensed under GPLv2. Since the GPLv2 license is incompatible with Apache-2.0 for redistribution in certain contexts, this creates a licensing conflict for using VideoGear in production.

@REBAUD Thank you for bringing up this licensing concern. I'd like to clarify the dependency relationship:

`yt-dlp` is actually an optional dependency that is only required by CamGear API when using video URLs as input sources. It is not a core requirement for VideoGear's main functionality. Users who don't need URL video processing can use VideoGear without installing `yt-dlp` or its dependencies.

Since this is a soft dependency that's only loaded when specifically using URL features, there is no direct licensing conflict with VideoGear's Apache-2.0 license. The optional nature of this dependency means users can choose whether to include `yt-dlp` based on their specific needs and licensing requirements.

If you have concerns about `yt-dlp`'s dependencies and licensing, I'd encourage you to raise this issue in the [yt-dlp repository](https://github.com/yt-dlp/yt-dlp) as they would be better positioned to address questions about their dependency chain and licensing implications.

Let me know if you have any other questions!
