### ISSUE TITLE
How can we to make transmit frame faster?

### ISSUE THREAD

**Issue by Julius-ZCJ** [abhiTronix/vidgear#47]
I  want to use this project's NetGear. When I use frame 10x10 pixel, sending time is 0.0065s per frame. Using 600x600 pixel, the spend time is 0.095s, And 1000x1000 is 0.26s. This is too slow. I want to have a real-time show about transmitting frame. what can we do to faster the transmitting time? 

I try to use asynic to improve transmitting speed, but I'm failed, as follow is my code:

```
async def send_img(server):

    # print('send the number is: ', queue.qsize())
    while True:
        if not queue.empty():
            frame = queue.get()
            print('sending....')
            frame = cv2.resize(frame)
            server.send(frame)


def main():
    print(os.getpid())
    pid = os.fork()
    if pid == 0:
        detection()
    else:

        options = {'copy': False, 'track': False}
        # change following IP address '192.168.1.xxx' with yours
        server = NetGear(address='192.168.10.189', port='5454', protocol='tcp', pattern=0, receive_mode=False,
                     logging=True, **options)  # Define netgear server at your system IP address.

        loop = asyncio.get_event_loop()
        loop.run_until_complete(send_img(server))
```

This is code segment, can anyone give some suggest? 
Thank you

**Comment by abhiTronix** [comment]
@Julius-ZCJ Don't use asyncio it won't help in this case. Here are few factors that may help you in improving speed significantly:
1. **Use only optimized VidGear APIs instead of OpenCV functions with NetGear API:** For example similar to this example sketch: https://github.com/abhiTronix/vidgear/wiki/NetGear#usage-with-other-vidgear-gears
2. **Use PUB/SUB pattern if you're live streaming**: Remember to use [**Publisher/Subscriber pattern**](https://learning-0mq-with-pyzmq.readthedocs.io/en/latest/pyzmq/patterns/pubsub.html) only for asynchronous high-speed messaging/transmission. Other messaging patterns such as Pair & Client/Server are only useful for slower synchronous transmission. You can set parameter [`pattern=2` during NetGear class initialization](https://github.com/abhiTronix/vidgear/wiki/NetGear#parameters-and-attributes-wrench) in your code to activate Publisher/Subscriber pattern.
3. **Use Wired connection instead of Wireless connection**: Remember typical 802.11g Wireless has a theoretical maximum of 54Mbps. Typical wired 10/100/1000 Ethernet has a theoretical maximum of 100 Gbps. So in theory wired is faster. However, these speeds are only on your local network. So chose your network configuration wisely

**Comment by Julius-ZCJ** [comment]
OK, Thank you ,I will try

**Comment by abhiTronix** [comment]
Closed. feel free to reopen if something doesn't worked for you.
