### ISSUE TITLE
Processing(opencv) and Streaming multiple IPCamera to the Client

### ISSUE THREAD

**Issue by SaddamBInSyed** [abhiTronix/vidgear#60]
Since I am new to this library, I want someone to help/advise me about **How to stream and do process(e.g: detect a face, motion detection etc) the connected multiple IP cameras videos to the web client?**

### Your Environment

* VidGear version: latest
* Branch: 
* Python version: 3.6.8
* pip version:
* Operating System and version: rasperry pi 3 and pi4 (4gb)
 

Please help

**Comment by abhiTronix** [comment]
@SaddamBInSyed 

1.  To get things started first throughly read [NetGear API Wiki](https://github.com/abhiTronix/vidgear/wiki/NetGear#netgear-api) which designed to transfer video frames & data synchronously (Pair & Client/Server) as well as asynchronously (Publish/Subscribe) between various interconnecting systems over the network in real-time  ZMQ messaging system. 
2. Since New features are as of now haven't available through pypi, therefore, you have to clone and install latest Vidgear as follows:
 ```sh
git clone https://github.com/abhiTronix/vidgear.git
cd vidgear
git checkout testing
sudo pip3 install .
cd
```
3. Then, You can use VidGear's exclusive [Multi-Server-Mode](https://github.com/abhiTronix/vidgear/wiki/Multi-Server-Mode-for-NetGear-API#multi-server-mode-for-netgear-api) exclusive designed NetGear API for robustly handling Multiple Servers at once, through exclusive Publish/Subscribe (zmq.PUB/zmq.SUB) messaging pattern, thereby providing access to seamless Live Streams across the various device in a network at the same time.

**Finally, if something doesn't work for you, report me here. Good luck!**

**Comment by abhiTronix** [comment]
@SaddamBInSyed  **Closing this issue and marked solved. Feel free to reopen if this solution doesn't work for you.**

**Comment by SaddamBInSyed** [comment]
@abhiTronix ,

Thank you so much for your response.

I carefully followed your instructions and output was a success.

I am building a home surveillance security system where many IP cameras used. 
So I would like your advice here to use your library in the below requirement.


![image](https://user-images.githubusercontent.com/10062672/67756789-14857c00-fa54-11e9-9516-1f6382f50209.png)

**Comment by abhiTronix** [comment]
@SaddamBInSyed Are all cameras connected directly/physically(i.e. directly by wire) to your local server(i.e. your Jatson Nano) or they are connected to your nano wirelessly? Also, VidGear processes each Video stream separately and optimizes performance via multi-threading, so no problem there.

**Comment by SaddamBInSyed** [comment]
@abhiTronix .

Yes, all are IP cameras connected with the POE switch.

Also, If add camera request comes from the Client then I want to start a separate process to process the IP camera stream.

if i use multithreading here Will not be slow down the performance of the server (single process).?

Is there any sample code for Vidgear to process multiple camera streams?

Thank you,

**Comment by abhiTronix** [comment]
@SaddamBInSyed , VidGear can handle any stream or any number of streams you can think of, it is designed for performance video processing. 

> Also, If add camera request comes from the Client then I want to start a separate process to process the IP camera stream.

Yes, you have to add a few lines of code for every new video stream, it can be easily done by  Secure shell a.k.a. SSH into your local server.

> if i use multithreading here Will not be slow down the performance of the server (single process).?

Multithreading is a leader when it comes down to performance on separate single process a.k.a threads as long as each thread don't interfere with each other. VidGear takes care that these threads are kept separated as far as possible with the help of performance queues a.k.a deques. So there won't be any performance issue if you're not running multiple instances of the same thread or interfering with any VidGear employed video stream with another python script. 

> Is there any sample code for Vidgear to process multiple camera streams?

Yep, it's pretty easy. See [this example code in my comment](https://github.com/abhiTronix/vidgear/issues/1#issuecomment-473943037), also everything runs synchronized as well. Goodluck
