### ISSUE TITLE
WriteGear from ScreenGear

### ISSUE THREAD

**Issue by FrancescoRossi1987** [abhiTronix/vidgear#63]
Follow this code:

```
# IMPORT  
from vidgear.gears import ScreenGear
from vidgear.gears import WriteGear
import cv2

# SHOW WINDOW
cv2.namedWindow('Output_Frame',cv2.WINDOW_NORMAL)

# SCREEN
options = {'top': 300, 'left': 300, 'width': 300, 'height': 200} 
stream = ScreenGear(monitor=1, logging=True, **options).start()

# WRITE
output_params = {"-input_framerate":25}
writer = WriteGear(output_filename = 'video_Screen2Write_example.mp4', logging = True, **output_params) 

# MAIN LOOP
while True: 
	
    # read frame from SCREEN
    frame = stream.read()
    if frame is None:
        break

    # show frame in window and WRITE
    cv2.imshow("Output_Frame", frame)
    writer.write(frame)

    # if 'q' then EXIT
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break


# CLOSE ALL
cv2.destroyAllWindows()
stream.stop()
writer.close()

```

After running for 30 seconds press "q" to stop. Then go to the saved file video, look at its Properties-> Duration. It will be much more than 30 seconds, with Framerate = 25.
(In fact during the writing process I see the speed>1.0x and the fps>25)

I suppose that  the reason is  that my writer is faster  than 25 fps, so it is able to screen at  higher framerate, generating a longer output video.

- - - - - - - - - - - 
NOTE:
If I set `output_params = {"-input_framerate":stream.framerate}`, where `stream = ScreenGear(monitor=1, logging=True, **options).start()`

I get:
_**AttributeError: 'ScreenGear' object has no attribute 'framerate'**_

- - - - - - - - - - - 

How can I use WRITE tacking video from SCREEN with a temporal coherence with a fixed framerate?

**Comment by abhiTronix** [comment]
@FrancescoRossi1987 **Kindly refrain from opening multiple issues of the same kind, you can reopen previous issue or comment there instead, otherwise, duplicated issues will be marked invalid and certainly be closed.**

> After running for 30 seconds press "q" to stop. Then go to the saved file video, look at its Properties-> Duration. It will be much more than 30 seconds, with Framerate = 25.

**Wrong**, the 25fps in the properties mean the video is encoded at constant 25-fps input framerate controlled by `-r`/`-framerate` input parameter in FFmpeg. You can learn more about it here:https://trac.ffmpeg.org/wiki/ChangingFrameRate It is not at all get affected by the speed at which frames write takes place or how fast frames being generated. 

> (In fact during the writing process I see the speed>1.0x and the fps>25)
> I suppose that the reason is that my writer is faster than 25 fps, so it is able to screen at higher framerate, generating a longer output video.

**You can't judge encoding speed just by watching frames. That's ridiculous.** Also like I said, WriteGear's writer, his just a high-level wrapper around FFmpeg Pipeline, and has nothing to do with the speed of writing or encoding. Therefore If you can achieve results with FFmpeg, then you can do the same here. 

> 
> NOTE:
> If I set output_params = {"-input_framerate":stream.framerate}, where stream = ScreenGear(monitor=1, logging=True, **options).start()
> 
> I get:
> AttributeError: 'ScreenGear' object has no attribute 'framerate'

**FYI, ScreenGear has no parameter called `stream.framerate` it is meant for CamGear/PiGear only, you can use value directly as `output_params = {"-input_framerate":25}` instead. ** Kindly read [VidGear Gear's Wiki](https://github.com/abhiTronix/vidgear/wiki#gears-what-are-these) properly before trying out simple things.

> How can I use WRITE tacking video from SCREEN with a temporal coherence with a fixed framerate?

 _"temporal coherence"_ has nothing to do here, as we aren't dealing with EM waves here.  If you're getting shorter length video then intended, then, you can try changing output parameters with `output_params = {"-r":25}` for constant output framerate instead of `output_params = {"-input_framerate":25}` in WriteGear. Try both and see which one is working for you.

**Comment by abhiTronix** [comment]
**Closed. Kindly elaborate your issue for further investigation and follow proper template for filing issue next time.**

**Comment by KenwoodFox** [comment]
Sorry for the delay, bit hectic, this seems to rly on webgear actually sending a frame for the recorder to save each frame. This makes the recording stop when the web-page is closed or connection is inturruped, can i make the writegear request new frames even without the webgear doing it?
